myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('sample2/<data>',views.sample2,name="sample2"),
    path("sample3/",views.sample3,name="sample3"),
]

pro8/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myapp.urls")),
    path('sample1/',views.sample1,name="sample1"),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render


# Create your views here.
def sample1(request):
    return render(request,"sample1.html")

def sample2(request,data):
    return render(request,"sample2.html",context={'data':data})

def sample3(request):
    return render(request,"sample3.html",context={'name':"kavya"})

templates/sample1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>page1</title>
</head>
<body>
    <h1>welcome to page1</h1>
    <a href="{% url 'myapp:sample2' data='Hello World' %}">sample2</a>
    <br><a href="{% url 'myapp:sample3' %}">sample3</a>
</body>
</html>

templates/sample2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width, initial-scale=1.0">
    <title>page2</title>
</head>
<body>
    <h1>welcome to page2</h1>
    <h2>iam carrying the data in url and the data is {{data}}</h2>
    <a href="{% url 'sample1' %}">sample1</a><br>
    <a href="{% url 'myapp:sample3' %}">sample3</a>
    
</body>
</html>

templates/sample3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>page3</title>
</head>
<body>
    <h1>welcome to page2</h1>
    <h2>iam carrying the data from backend  {{name}}</h2>
    <a href="{% url 'sample1' %}">sample1</a><br>
    <a href="{% url 'myapp:sample2' data=name %}">sample2</a>
    
</body>
</html>